;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        keyboard-escape-quit
        ))

(setq mc/cmds-to-run-once
      '(
        complete-symbol
        end-of-buffer
        mc/mark-prev-like-this
        ))
