;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        indent-for-tab-command
        sgml-slash
        ))

(setq mc/cmds-to-run-once
      '(
        handle-switch-frame
        helm-show-kill-ring
        keyboard-escape-quit
        mark-whole-buffer
        mouse-set-secondary
        previous-buffer
        term-send-down
        term-send-left
        term-send-raw
        xref-pop-marker-stack
        ))
